---
driver:
  name: ec2
  region: ${region}
  aws_ssh_key_id: ${ssh_key_id}
  availability_zone: b
  require_chef_omnibus: true
  associate_public_ip: true
  instance_type: ${instance_type}
  interface: dns

transport:
  ssh_key: ~/.ssh/${ssh_key_id}
  connection_timeout: 10
  connection_retries: 5

provisioner:
  name: chef_zero

platforms:
  - name: ${ec2_platform_name}

suites:
  - name: default
    run_list:
      - recipe[the-cookbook::default]
      - recipe[development-cookbook::desktop]
    attributes:
      vnc:
        account_username: ${vnc_username}
        account_password: ${vnc_password}
      development:
        files_url: ${ftp_url}
        workspace: ~/workspace
        mysql_version: ${mysql_version}
      java:
        jdk_version: ${open_jdk_version}
      idea:
        version: ${intellij_version}
        setup_dir: /opt
        64bits:
          Xmx: ${intellij_Xmx}
          Xms: ${intellij_Xms}
